apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: research-platform-prod
resources:
  - namespace.yaml
  - ../../base
commonLabels:
  environment: prod
images:
  - name: ghcr.io/PLACEHOLDER_ORG/research-platform
    newTag: prod
